stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - experiments/gender_classification_v7.csv
    outs:
      - output/test_data.csv 
      - output/train_data.csv 

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - output/train_data.csv
    outs:
      - preprocessed_data/preprocessed_data.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - preprocessed_data/preprocessed_data.csv 
    outs:
      - features/x_test.csv 
      - features/x_train.csv 
      - features/y_test.csv 
      - features/y_train.csv 

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py 
      - features/x_train.csv
      - features/y_train.csv 
    outs:
      - models/model.pkl 

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py 
      - models/model.pkl 
    outs:
      - evaluation_results/evaluation_results.json